### ISSUE TITLE
Error with Browserify bundle file

### ISSUE THREAD

**Issue by khoaho** [Autodesk-Forge/forge.oss-js#1]
Hi Cyrille,

I follow instruction to install forge-oss with npm and run `browserify main.js > bundle.js`, with main.js is either callback version or Promise version. The file main.js also has "YOUR ACCESS TOKEN" getting from Forge OAuth with `scope = bucket:create`.

The HTML test file of bundle.js is very simple as:

``` html
<html>
<head>
</head>
<body>
    <script src="bundle.js"></script>
</body>
</html>
```

However, it gets error at api.createBucket:

> XMLHttpRequest cannot load https://developer.api.autodesk.com/oss/v2/buckets. Request header field x-ads-region is not allowed by Access-Control-Allow-Headers in preflight response.

Could you please check the bundle.js created from Browserify.

Thank you,
Khoa

**Comment by leefsmp** [comment]
This is a library designed to be used on a server-side node.js application, not supposed to be used on the client-side as it will require exposing your credentials
